Application/SchoolManagementSystem/SchoolManagementSystem/Controllers/StudentTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DatabaseAccess;

namespace SchoolManagementSystem.Controllers
{
    public class StudentTablesController : Controller
    {
        private SchoolMgtDbEntities db = new SchoolMgtDbEntities();

        // GET: StudentTables
        public ActionResult Index()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            var studentTables = db.StudentTables.Include(s => s.ClassTable).Include(s => s.ProgrameTable).Include(s => s.SessionTable).Include(s => s.UserTable);
            return View(studentTables.ToList());
        }

        // GET: StudentTables/Details/5
        public ActionResult Details(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentTable studentTable = db.StudentTables.Find(id);
            if (studentTable == null)
            {
                return HttpNotFound();
            }
            return View(studentTable);
        }

        // GET: StudentTables/Create
        public ActionResult Create()
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            ViewBag.ClassID = new SelectList(db.ClassTables, "ClassID", "Name");
            ViewBag.Programe_ID = new SelectList(db.ProgrameTables, "ProgrameID", "Name");
            ViewBag.Session_ID = new SelectList(db.SessionTables, "SessionID", "Name");
            ViewBag.User_ID = new SelectList(db.UserTables, "UserID", "FullName");
            return View();
        }

        // POST: StudentTables/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentID,Session_ID,Programe_ID,User_ID,ClassID,Name,FatherName,DateofBirth,Gender,ContactNo,Photo,AddmissionDate,PreviousSchool,PreviousPercentage,EmailAddress,Address,Nationality")] StudentTable studentTable, HttpPostedFileBase image)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            int userId = Convert.ToInt32(Convert.ToString(Session["UserID"]));
            studentTable.User_ID = userId;
            studentTable.Photo = "/Content/StaffPhoto/default.png";

            if (image != null)
            {
                string fileName = image.FileName;
                string _path = Path.Combine(Server.MapPath("/Content/StudentPhoto"), fileName);
                image.SaveAs(_path);
                studentTable.Photo = "/Content/StudentPhoto/" + fileName;
            }

            if (ModelState.IsValid)
            {

                db.StudentTables.Add(studentTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClassID = new SelectList(db.ClassTables, "ClassID", "Name", studentTable.ClassID);
            ViewBag.Programe_ID = new SelectList(db.ProgrameTables, "ProgrameID", "Name", studentTable.Programe_ID);
            ViewBag.Session_ID = new SelectList(db.SessionTables, "SessionID", "Name", studentTable.Session_ID);
            ViewBag.User_ID = new SelectList(db.UserTables, "UserID", "FullName", studentTable.User_ID);
            return View(studentTable);
        }

        // GET: StudentTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentTable studentTable = db.StudentTables.Find(id);
            if (studentTable == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClassID = new SelectList(db.ClassTables, "ClassID", "Name", studentTable.ClassID);
            ViewBag.Programe_ID = new SelectList(db.ProgrameTables, "ProgrameID", "Name", studentTable.Programe_ID);
            ViewBag.Session_ID = new SelectList(db.SessionTables, "SessionID", "Name", studentTable.Session_ID);
            ViewBag.User_ID = new SelectList(db.UserTables, "UserID", "FullName", studentTable.User_ID);
            return View(studentTable);
        }

        // POST: StudentTables/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentID,Session_ID,Programe_ID,User_ID,ClassID,Name,FatherName,DateofBirth,Gender,ContactNo,Photo,AddmissionDate,PreviousSchool,PreviousPercentage,EmailAddress,Address,Nationality")] StudentTable studentTable, HttpPostedFileBase image)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            int userId = Convert.ToInt32(Convert.ToString(Session["UserID"]));
            studentTable.User_ID = userId;

            if (image != null)
            {
                string fileName = image.FileName;
                string _path = Path.Combine(Server.MapPath("/Content/StudentPhoto"), fileName);
                image.SaveAs(_path);
                studentTable.Photo = "/Content/StudentPhoto/" + fileName;
            }

            if (ModelState.IsValid)
            {
                db.Entry(studentTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            ViewBag.ClassID = new SelectList(db.ClassTables, "ClassID", "Name", studentTable.ClassID);
            ViewBag.Programe_ID = new SelectList(db.ProgrameTables, "ProgrameID", "Name", studentTable.Programe_ID);
            ViewBag.Session_ID = new SelectList(db.SessionTables, "SessionID", "Name", studentTable.Session_ID);
            ViewBag.User_ID = new SelectList(db.UserTables, "UserID", "FullName", studentTable.User_ID);
            return View(studentTable);
        }

        // GET: StudentTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (string.IsNullOrEmpty(Convert.ToString(Session["UserName"])))
            {
                return RedirectToAction("Login", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudentTable studentTable = db.StudentTables.Find(id);
            if (studentTable == null)
            {
                return HttpNotFound();
            }
            return View(studentTable);
        }

        // POST: StudentTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StudentTable studentTable = db.StudentTables.Find(id);
            db.StudentTables.Remove(studentTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

      
    }
}

Application/SchoolManagementSystem/SchoolManagementSystem/Views/StudentTables/Create.cshtml
@model DatabaseAccess.StudentTable

@{
    ViewBag.Title = "Create";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Add A New Student</h6>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Create", "StudentTables", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()


            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group row">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.Session_ID, "Session_ID", htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.DropDownList("Session_ID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Session_ID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.Programe_ID, "Programe_ID", htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.DropDownList("Programe_ID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Programe_ID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">

                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.ClassID, "ClassID", htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.DropDownList("ClassID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ClassID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">

                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.FatherName, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.FatherName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FatherName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.DateofBirth, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.DateofBirth, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DateofBirth, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group row">

                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @*@Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })*@
                            @Html.DropDownList("Gender", new List<SelectListItem>
                        {
                            new SelectListItem{ Text="Male", Value="Male"},
                            new SelectListItem{ Text="Female", Value="Female"}
                        }, "--- Select ---", new { @class = "form-control" })

                        </div>
                    </div>
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">

                    <div class="col-lg-5">
                        @*@Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
                        </div>*@
                        @Html.LabelFor(model => model.PhotoFile, "Select Photo", htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            <input type="file" name="Image" id="Image" style="width: 100%;" />
                        </div>
                    </div>

                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.AddmissionDate, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.AddmissionDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.AddmissionDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>


                <div class="form-group row">

                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.PreviousSchool, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.PreviousSchool, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PreviousSchool, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.PreviousPercentage, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.PreviousPercentage, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PreviousPercentage, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">

                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>


                <div class="form-group row">

                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.Nationality, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.Nationality, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nationality, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-success" />
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-defaut" })

                    </div>
                </div>
            </div>
        }

    </div>
</div>

Application/SchoolManagementSystem/SchoolManagementSystem/Views/StudentTables/Delete.cshtml
@model DatabaseAccess.StudentTable

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>StudentTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FatherName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FatherName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateofBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateofBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Photo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddmissionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddmissionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PreviousSchool)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PreviousSchool)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PreviousPercentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PreviousPercentage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nationality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClassTable.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassTable.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProgrameTable.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgrameTable.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SessionTable.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SessionTable.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserTable.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserTable.FullName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Application/SchoolManagementSystem/SchoolManagementSystem/Views/StudentTables/Edit.cshtml
@model DatabaseAccess.StudentTable

@{
    ViewBag.Title = "Edit";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Add A New Student</h6>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("Edit", "StudentTables", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.StudentID)

                <div class="form-group row">
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.Session_ID, "Session_ID", htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.DropDownList("Session_ID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Session_ID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.Programe_ID, "Programe_ID", htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.DropDownList("Programe_ID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Programe_ID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">

                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.ClassID, "ClassID", htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.DropDownList("ClassID", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ClassID, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">

                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.FatherName, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.FatherName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FatherName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.DateofBirth, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.DateofBirth, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.DateofBirth, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group row">

                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @*@Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })*@
                            @*@Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })*@
                            @Html.DropDownList("Gender", new List<SelectListItem>
                            {
                                new SelectListItem{ Text="Male", Value="Male"},
                                new SelectListItem{ Text="Female", Value="Female"}
                            }, "--- Select ---", new { @class = "form-control" })


                        </div>


                    </div>
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">

                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.PhotoFile, "Select Photo", htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col-md-10">
                            <input type="file" name="Image" id="Image" style="width: 100%;" />
                        </div>
                    </div>
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.AddmissionDate, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.AddmissionDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.AddmissionDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>


                <div class="form-group row">

                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.PreviousSchool, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.PreviousSchool, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PreviousSchool, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.PreviousPercentage, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.PreviousPercentage, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PreviousPercentage, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group row">

                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>


                <div class="form-group row">

                    <div class="col-lg-5">
                        @Html.LabelFor(model => model.Nationality, htmlAttributes: new { @class = "control-label col-md-5" })
                        <div class="col">
                            @Html.EditorFor(model => model.Nationality, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Nationality, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-success" />
                        @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-defaut" })

                    </div>
                </div>
            </div>
        }

    </div>
</div>